[package]
name = "eform"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.21.3", features = ["persistence", "dark-light"] }
serde = { version = "1.0.158", features = ["derive"] }
